// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Pack } from "./Pack";

/**
 * One catalog card for the «Дополнения» screen.
 */
export type Addon = { pack: Pack, installed: boolean, 
/**
 * Ships switched on (`packs/*.json`, «Команды по умолчанию»), can't be removed.
 */
default: boolean, };
