// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One model the user added in Settings → ИИ. The list order is the priority.
 */
export type AiSlot = { 
/**
 * [`Provider::id`].
 */
provider: string, key: string, 
/**
 * Empty = the provider's default model(s).
 */
model: string, 
/**
 * Only for `custom`: an OpenAI-compatible chat/completions URL (Ollama, LM Studio…).
 */
url: string, };
