// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AssistantState = "idle" | "listening" | "processing" | "speaking" | "mic_off";
