// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";
import type { Reply } from "./Reply";
import type { When } from "./When";

export type Command = { id: string, folder: Array<string>, name: string, 
/**
 * At least one must be said.
 */
phrases: Array<string>, 
/**
 * May or may not be said.
 */
optional: Array<string>, actions: Array<Action>, reply: Reply, 
/**
 * Ask before running (§4.6); dangerous actions force it anyway.
 */
confirm: boolean, 
/**
 * May take part in «… и …» chains (§4.3).
 */
chainable: boolean, slots: { [key in string]: string }, when: When | null, 
/**
 * Switched off in the editor: kept, but never matched.
 */
enabled: boolean, };
