// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Reply } from "./Reply";
import type { Status } from "./Status";
import type { StepResult } from "./StepResult";

export type CommandOutcome = { id: string, name: string, status: Status, steps: Array<StepResult>, reply: Reply, };
