// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hotkeys } from "./Hotkeys";
import type { ModePhrases } from "./ModePhrases";
import type { Online } from "./Online";
import type { UiPrefs } from "./UiPrefs";
import type { VoiceEngine } from "./VoiceEngine";

export type Config = { 
/**
 * Commands only after "Джарвис" (§2.2).
 */
prefix_mode: boolean, 
/**
 * No voice replies, only sound + visuals (§2.2).
 */
silent_mode: boolean, 
/**
 * Microphone fully closed when false (§2.2).
 */
mic_enabled: boolean, 
/**
 * Capture device name; `None` = system default.
 */
mic_device: string | null, 
/**
 * Wake word threshold slider, 0–100 (§2.2).
 */
wake_sensitivity: number, 
/**
 * Listening window after wake word, seconds (§2.1).
 */
listen_timeout_sec: number, 
/**
 * Follow-up window without wake word, seconds (§2.1).
 */
followup_sec: number, 
/**
 * Keep Vosk loaded after a command, seconds (§1).
 */
stt_keep_warm_sec: number, 
/**
 * Unload models on idle timers; off = keep Vosk warm always (§12).
 */
memory_saver: boolean, 
/**
 * Jarvis voice volume, 0–100 (§3.4).
 */
voice_volume: number, 
/**
 * «Сворачивать в трей при закрытии» (§10.4): close destroys the WebView, core keeps running.
 */
close_to_tray: boolean, 
/**
 * «Автозапуск программы» (§10.4).
 */
autostart: boolean, 
/**
 * Voice engine card on «Синтез речи» (§6.4).
 */
voice_engine: VoiceEngine, 
/**
 * Neural voice speed, 0.5–2.0 (§6.4).
 */
voice_speed: number, 
/**
 * «Как в фильме» EQ + reverb on the neural voice (§6.2).
 */
voice_fx: boolean, hotkeys: Hotkeys, 
/**
 * Look & feel (§3.1, §10.4 «Интерфейс»), applied by the UI.
 */
ui: UiPrefs, 
/**
 * Voice phrases that switch modes (§2.2), editable in settings.
 */
mode_phrases: ModePhrases, 
/**
 * Online keys (Settings → ИИ): stay in this PC's config.json, never in git.
 */
online: Online, 
/**
 * The first-run greeting («первичная настройка… калибровка… все системы штатно») played.
 */
introduced: boolean, };
