// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Confirmation dialog (SPEC §4.6).
 */
export type ConfirmRequest = { question: string, timeout_sec: number, };
