// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssistantState } from "./AssistantState";
import type { HistoryEntry } from "./HistoryEntry";
import type { Level } from "./Level";
import type { Transcript } from "./Transcript";

export type CoreEvent = { "event": "state", "payload": AssistantState } | { "event": "transcript", "payload": Transcript } | { "event": "history", "payload": HistoryEntry } | { "event": "level", "payload": Level };
