// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssistantState } from "./AssistantState";
import type { ConfirmRequest } from "./ConfirmRequest";
import type { HistoryEntry } from "./HistoryEntry";
import type { Level } from "./Level";
import type { Outcome } from "./Outcome";
import type { Transcript } from "./Transcript";
import type { UiCommand } from "./UiCommand";

export type CoreEvent = { "event": "state", "payload": AssistantState } | { "event": "transcript", "payload": Transcript } | { "event": "history", "payload": HistoryEntry } | { "event": "level", "payload": Level } | { "event": "confirm", "payload": ConfirmRequest } | { "event": "confirm_closed" } | { "event": "outcome", "payload": Outcome } | { "event": "say", "payload": string } | { "event": "ui", "payload": UiCommand };
