// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Command } from "./Command";

export type Entry = { command: Command, 
/**
 * Comes from a built-in pack (can't be deleted, only edited/switched off).
 */
builtin: boolean, 
/**
 * Built-in overridden by the user pack.
 */
modified: boolean, 
/**
 * Why the brain would skip it (empty = valid).
 */
issues: Array<string>, };
