// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Status } from "./Status";

export type HistoryEntry = { id: number, 
/**
 * Unix time, milliseconds.
 */
ts: number, phrase: string, command_id: string | null, status: Status, };
