// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Hotkeys = { push_to_talk: string, toggle_window: string, toggle_mic: string, };
