// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Audio levels 0.0–1.0 for orb/listening bar.
 */
export type Level = { mic: number, tts: number, };
