// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Entry } from "./Entry";

export type Library = { entries: Array<Entry>, folders: Array<Array<string>>, };
