// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModePhrases = { prefix_on: string, prefix_off: string, silent_on: string, silent_off: string, mic_off: string, };
