// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModeCommand = "prefix_on" | "prefix_off" | "silent_on" | "silent_off" | "mic_on" | "mic_off";
