// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Online = { 
/**
 * Google AI Studio keys for the news digest; the second is used when the first hits its quota.
 */
gemini_keys: Array<string>, gemini_model: string, 
/**
 * Fish Audio key: any text without a recording is spoken in the Jarvis voice online.
 */
fish_key: string, fish_voice: string, };
