// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiSlot } from "./AiSlot";

export type Online = { 
/**
 * Google AI Studio keys for the news digest; the second is used when the first hits its quota.
 */
gemini_keys: Array<string>, gemini_model: string, 
/**
 * Fish Audio key: any text without a recording is spoken in the Jarvis voice online.
 */
fish_key: string, fish_voice: string, 
/**
 * ElevenLabs key: when set, it voices text instead of Fish (studio-grade Russian).
 */
eleven_key: string, 
/**
 * Voice ID from elevenlabs.io (premade or Voice Library).
 */
eleven_voice: string, 
/**
 * Chat models for the digest and free questions, in priority order (Settings → ИИ).
 * The Gemini keys above are tried after them.
 */
ai: Array<AiSlot>, 
/**
 * Google Cloud OAuth «Desktop app» client for Classroom homework.
 */
classroom_id: string, classroom_secret: string, 
/**
 * Refresh token from «Подключить» (set by the app, kept on UI saves).
 */
classroom_token: string, };
