// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandOutcome } from "./CommandOutcome";

export type Outcome = { phrase: string, 
/**
 * Empty = not understood.
 */
commands: Array<CommandOutcome>, };
