// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Command } from "./Command";

export type Pack = { id: string, name: string, description: string, category: string, version: string, 
/**
 * Add-on card (§9): brand key for the app icon, its colour, «Популярное» shelf.
 */
icon?: string, color?: string, popular?: boolean, commands: Array<Command>, 
/**
 * Folders the editor keeps even while empty (user pack only).
 */
folders: Array<Array<string>>, };
