// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Command } from "./Command";

export type Pack = { id: string, name: string, description: string, category: string, version: string, commands: Array<Command>, };
