// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Editor live preview row (§5.3): the command a sample phrase reaches.
 */
export type Probe = { text: string, 
/**
 * First command the brain would run; `None` = not understood.
 */
id: string | null, name: string | null, };
