// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Reply = { 
/**
 * Voice pack categories (§6.1), random pick: `ok`, `done`, `loading`…
 */
clips: Array<string>, text: string | null, };
