// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SlotValue = { "kind": "number", "value": number } | { "kind": "duration", "value": number } | { "kind": "text", "value": string };
