// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StepResult = { 
/**
 * Action type, e.g. `Launch.File`.
 */
action: string, ok: boolean, error: string | null, 
/**
 * Text to speak/show (System.Info, clipboard…).
 */
output: string | null, };
