// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Transcript = { text: string, 
/**
 * false = partial result (listening bar), true = final utterance.
 */
is_final: boolean, };
