// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Assistant actions that drive the UI.
 */
export type UiCommand = { "kind": "open_page", "value": string } | { "kind": "set_theme", "value": string };
