// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UiPrefs = { 
/**
 * Accent `#rrggbb` (theme swatches or custom).
 */
accent: string, 
/**
 * Window transparency, 0–100 % (Mica/CSS).
 */
transparency: number, 
/**
 * Glass blur, 0–100 %.
 */
blur: number, animations: boolean, avatar: boolean, hud: boolean, on_top: boolean, };
