// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Initial state for the main window (control panel, dashboard counter).
 */
export type UiSnapshot = { prefix_mode: boolean, silent_mode: boolean, mic_enabled: boolean, voice_volume: number, commands: number, };
