// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type When = { 
/**
 * Foreground process exe, e.g. `POWERPNT.EXE`; several as `WINWORD.EXE|POWERPNT.EXE` (§4.5).
 */
foreground: string | null, };
